ConvertFrom-StringData @' 
 ScopedItemOptions="Les valeurs {0} et {1} sont exclusives."
 EVAGlobbing="Le globbing (?,*,[]) n'est pas supporté ({0})."
 ProviderConstraintRequiereAddLib="Requiere certains scripts du projet Add-Lib."
 ProviderConstraint="Seul le provider {0} est autorisé pour le chemin :`r`n{1}."
 PathMustExistNullOrEmpty="Le nom de chemin est null ou vide."
 PathMustExist="Le nom de chemin n'existe pas : {0}"
 IsSubClassOf="L'argument {0} n'est pas une instance dérivée de la classe {1}."
 IsWMIClassIsSubClassOf="La classe de l'argument {0} n'est pas dérivée de [System.Management.ManagementBaseObject]."
 IsWMIClass="L'argument n'est pas une instance de la classe WMI {0}"
 IsImplementingInterfaceIsNotAnInterface="La classe {0} ne représente pas un type d'interface."
 IsImplementingInterface="La classe {0} n'implémente pas l'interface {1}."
 ServiceStatusUnknown="Le service {0} est inconnu."  
 ServiceStatus="Le service {0}({1}) n'est pas {2}.`n`rImpossible de continuer."
'@ 
